# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-02-05 12:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sales',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
